#!/bin/bash

if [[ "$1" != "-n" ]]; then
    nohup "$0" -n &
    exit $?
fi


for ((i = 0 ; i < 10 ; i++)); do

sleep 10
  json=$(curl -s -u "Dragonkiller69":github2018 https://api.github.com/repos/tpi135-2019/MantenimientoDatosTaller/events | jq '.[2]')

pullnumber=$(echo $json | jq '.payload.pull_request.number')
pullrequest=$(cat nohup.out)

if [[ $json != null ]] && [[ $(echo $json | jq '.type') == '"PullRequestEvent"' ]] && [[ $(echo $json | jq '.payload.action') == '"closed"' ]] && [[ $(echo $json | jq '.payload.pull_request.merged') == true ]] && [[ $pullrequest -lt $pullnumber ]]; then
   
    echo "Ejecutando pipeline" 
    curl http://localhost:9090/job/pipeline_tpi/build\?token\=pipeline
    echo $pullnumber > nohup.out
    exit
fi

done




